language: ruby
rvm:
  - 2.0.0
bundler_args: "--without production"
addons:
  postgresql: '9.3'
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script:
  - bundle exec rspec
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: xCIKfTnz0d1PL2PYs75DouGQ/gRaB2+zbEBFOyChBavkMqslo+uESW2UlFSyS6fDCzkYF7oHxo31GuwBDceQB+ec3o0zgXpuFVIaStWeixsB9cXUKk/+/9RX4MLx5ZMdvO4tF9orVYIEQdgx6vi1agA6sv8txcwoY4h45ACah9/gcN8k8nhKRJ6fwmhJNP0XiQbr5LlJW3YNAJpc5sxh9nq1d3tw4R0yHHEF69QWkj1yqBdQT5uPFwArCaR45T38neAEXaz+PusjoLGSnyCegdDzCtVkAlzT5BsGZqt4wg2eYcMbxhOQIAvSAoId7Kf/QROJUzKfZHQLdBL+Bk64+qzIxwZULXI2UCQYcpfd434mL29izNG+xenYizcs16/2b4yLvihzfXq2pXzhPhlO2N9EafItacvtbjs692oinYK79+XbnA4swmqZyBGB/fN6Hdqx2Cjx0qzliYwom7699Z7TuvvpuBtmsQaIdkU9A5GGdchHqu+5iBxQbxYOpgROpsLn+3s7krnfsiD53kZbfac/VOHDz+BZ3O5W8FLv3UzlfL+U9UTEUrx/nxCF3KFJxv+M8+75RwIhJqZ9r7/vWv+JcN6+p2yeUVQ8zz8JfWVsAQiHFEAIdQu3HL3s9F3W2NCsV9Qv72KHxdk6qE3nijrLvIlpcwIGyYp9DPmZDXc=
  app: limitless-ravine-97086
  on:
    repo: CarolinaSantana/shoeaddict_app
  run: "rake db:migrate"
env:
  global:
  - secure: Sl7leiD9cZt9kye3R/VLX/9z8lI3SsrdNSvvxhWvKWoo1QV+jtOKjWgfbfkckx0c3WUU3X16gkNiAhtz/mVEA3LyQY9XONVwu3gf1yL/5uxDrWR0AxkXATeBhcCaZ+8YjMD9/AtVUd7XueJ2FXD8g2jO7pusKcuH0zhhRTSt+CwvpPZtMz6u0VNDuotcZk9bO+hydIW14GYvKZtV+Ik7tdAexTWcqmKOr1yWz3UDmlRQ72u7Yvnjg3Gily5wt9LQ0Bf2+q8Ze4vL78/x9tXYWVAIpqRMxNZ2ExXJViaeeato/qNrmP4jjr75sRY72U8oJj2EXtmM2NevNFOd9tQOwGMnqS71QiFlKhvDYXJ9xUV5d33iTPlYm61ifgtrJfqOz6q0/95Wk2RhB5gBvDudUPIPHKH1Qn0+/+1C5xlHGnWDIXYhsf/5MB1iMNE0Mq8K0pNhyrRmxq/n4bp90WH6UVDx2xRaeSzTNErdBPbW0faZk/u2cNtBHdE+sq8XcvWrWHJ8dT3n8bhOM9T9fJ31tPsjS6f+rQy5j4+/efRAKXkBM3lPjlARMT1KicsUMqTntVWoz8gIzF/AiaJEYGA7xfzDgh9wIW5bhhKnNkuMpqpmOu6lrsi903wGB/Ewz5vbROkTWkNAhURGUs4PtOPJv6Y7OIw4MMdnaf25EZOH0IA=
  - secure: dVQs3e3o6dr2ZtEdBZ8vhC/ll+Ho0tZ2bhs5vMKqWmQxQQmRG0cVCN8169lRtZW8mKfhYQDU4r9lkyoAnjgc1bEmw3YBlexu9jikUHlFJigsTogh9F2LoeNvL/FqlTLMKhKCHrDm9ag1FrAH0SBOnEZho4uPwA51DwU5pdyqagXsHdA+/40H0+x6ZIqLrhE7u0+48MqLpxYgujkzCcpDGGlSRVW2la+KTpqJhTwluMaW74r+/lwbXXlQQNDG48rCPiToX/ia0kzBAhWsitI9euyEQqR/LWx4Jek16CJypghpDwd5DfAQH2x3NXmfnhe+vL0xdKLNLRT5lne4FqxO9fYFI+G/E1vuAbFW1SA9ZV3482Y5LGL9JEQdPBXADeb0lPvHP66ovkRHPu5ErVStg6Fl2NRcihXQUgokH9OEAkrHm8nUcC3J1BEYZ5D9Ngz9zYXAZpNlZnIZcrNLLK4lo1kbSe/OWaRbbc99aX1uCbe7/jXSvKiwk8ZBx8onjibyYFrtek/eTG1zHxoIud7cQCYZ2r1+VpH/K76yQdPheZRVVpqluv4Vxov37n9MQPChHgrPuV5ROKUUcKLOVksYHyMf0O6EjRf5v1Yu69ArDBy7p2uS4iUE35Aq7OPb4YoHTBeMHOjmfARdaP2s8xFsNruWFqFtAcat65hDXeX5jmE=
